### PR TITLE
Use separate instance type for green & blue.

### PR DESCRIPTION
**Pull request by ringods**
Use separate instance type for blue & green setups. Given the ability for custom termination policies, a change of the instance type prevents changes on the existing setup. This way, we can safely do a blue-green flip to change the instance type.

### CODE REVIEW

**Comment by SamClinckspoor** [comment]
Is this needed? if you change the launchconfig, the instances are not affected.

**Comment by MattiasGees** [comment]
Indeed I feel the same what @SamClinckspoor says.

**Comment by ringods** [comment]
@SamClinckspoor it is needed. Look at the production termination policy for SurveyAnyplace:

https://github.com/skyscrapers/surveyanyplace/blob/7fadb9f97dd9170431f2645a6b2dd069a1d52a04/terraform/production/api/main.tf#L33

Changing the instance type there would also impact the existing setup.

**Comment by MattiasGees** [comment]
@ringods A change in launchconfig doesn't cause a scale action, unless you force it. So the termination_policy has no effect on this.

**Comment by SamClinckspoor** [comment]
@ringods I don't think that is true, it is only the order in which they will be terminated if you scale down.

**Comment by ringods** [comment]
I hope you guys are right...

**Pull request closed without merging**
