### PR TITLE
add assume sts for cross accounts runs

### PR DESCRIPTION
**Pull request by minniux**
Add condition to assume role when `AWS_ACCOUNT_ID` is set
Used for cross accounts concourse runs

### CODE REVIEW

**Comment by ringods** [comment]
@minniux can't we keep this simpler by just deploying an additional Concourse worker in the target AWS account?

**Comment by minniux** [comment]
@ringods not really sure, currently that's already used in inventivedesigners as they use separate account per environment, and now I'm adding it for sweepbright, as they're using our internal concourse to save costs

**Comment by ringods** [comment]
@minniux then I would definitely deploy a tagged EC2 worker in their account and let that worker connect back to our Concourse-web container. Their worker will normally have the proper IAM instance role normally. No need for AssumeRole setup as a result.

**Comment by ringods** [comment]
Here is an example on how to configure both the resources and the tasks to run on a tagged worker:

https://github.com/concourse/pipelines/blob/master/airbus.concourse.ci/josh-is-cool/tagged-worker.yml

**Comment by minniux** [comment]
@ringods a separate worker just for packer builds? feels a little too much for sweepbright's use case, I guess might be for others as well, and same goes for inventivedesigners for their environments accounts (I was planning to switch ID to this script as well once live, they're using the exact setup)
Also, I can't get your point against the AssumeRole setup, can you elaborate?

**Comment by ringods** [comment]
@minniux simplicity & security.

Together with @venturel, @iuriaranda and @MattiasGees we already discussed further how a Concourse should be deployed network wise in a multi-environment setup. The Concourse web part, together with Vault and Teleport will be deployed in a `tools` environment, but I'm more in favor of deploying workers in the correct account and environment (VPC) then setting up cross-account permissions all over the place.

This PR goes against this vision. ID should be adapted later to a setup where the workers are running in the correct account. 

When running from within the correct account, it also has the advantage to e.g. set up MySQL/PostgreSQL databases with terraform on Concourse without a requirement for an SSH tunnel via the bastion because it is running from a worker within the VPC.

**Comment by minniux** [comment]
alright, got that.. Closing the PR then

**Pull request closed without merging**
