### PR TITLE
remove type tag in asg definition

### PR DESCRIPTION
**Pull request by venturel**
This PR is to remove the `type` tag as it's not really needed and it might be misleading

### CODE REVIEW

**Comment by iuriaranda** [comment]
Why is this needed? Can't you just use the `name` variable?

**Comment by venturel** [comment]
@iuriaranda no, because for some reason the name has been refactored in this PR https://github.com/skyscrapers/terraform-bluegreen/pull/25 and it can't be used as type

**Comment by iuriaranda** [comment]
What's the `Type` tag used for?

**Comment by venturel** [comment]
Good question, TBH I think it's not needed. I'd either remove it or change it as per this PR

**Comment by venturel** [comment]
I completely agree, changing the PR

**Pull request merged**
